ARG FROM
FROM ${FROM}

# google-noto-sans-cjk-ttc-fonts is for RHEL8
#RUN yum -y install vlgothic-p-fonts \
# || yum -y install google-noto-sans-cjk-ttc-fonts \
# && yum clean all

EXPOSE 80

# remote debug
EXPOSE 4002/tcp
