version: '3'

services:
    manager:
        build:
            context: manager/${MANAGER_MAJOR}/${MANAGER_MINOR}/${MANAGER_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=frooprogrammer/hinemos-manager-base-${MANAGER_MAJOR}.${MANAGER_MINOR}-openjdk${JAVA_VER}-${OS_IMAGE}
                #- FROM_TAG=frooprogrammer/hinemos-manager-restored-${MANAGER_MAJOR}.${MANAGER_MINOR}-openjdk${JAVA_VER}-${OS_IMAGE}
        image: hinemos-manager-${MANAGER_MAJOR}.${MANAGER_MINOR}:${MANAGER_TAG}
        ports:
            - '8080-8082:8080-8082'
            - '514:514'
            - '514:514/udp'
            - '162:162/udp'
            - '4000:4000'
        hostname: hinemos_manager
        networks:
            hinemos-net:
                ipv4_address: 172.31.1.10
        #network_mode: host
        extra_hosts:
            - docker-host:${LOCAL_IP}
        container_name: hinemos-manager
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_RESOURCE
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

    agent:
        build:
            context: agent/${AGENT_MAJOR}/${AGENT_MINOR}/${AGENT_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=frooprogrammer/hinemos-agent-base-${AGENT_MAJOR}.${AGENT_MINOR}-openjdk${JAVA_VER}-${OS_IMAGE}
        image: hinemos-agent-${AGENT_MAJOR}.${AGENT_MINOR}:${AGENT_TAG}
        ports:
            - '161:161/udp'
            - '24005:24005/udp'
            - '4001:4001'
        hostname: hinemos-agent
        networks:
            hinemos-net:
                ipv4_address: 172.31.1.11
        #network_mode: host
        extra_hosts:
            - docker-host:${LOCAL_IP}
        container_name: hinemos-agent
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

    web:
        build:
            context: web/${WEB_MAJOR}/${WEB_MINOR}/${WEB_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=frooprogrammer/hinemos-web-base-${WEB_MAJOR}.${WEB_MINOR}-openjdk${JAVA_VER}-${OS_IMAGE}
        image: hinemos-web-${WEB_MAJOR}.${WEB_MINOR}:${WEB_TAG}
        ports:
            - '80:80'
            #- '443:443'
        hostname: hinemos_web
        networks:
            hinemos-net:
                ipv4_address: 172.31.1.12
        extra_hosts:
            - docker-host:${LOCAL_IP}
        container_name: hinemos-web
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

networks:
    hinemos-net:
        ipam:
            driver: default
            config:
                - subnet: 172.31.1.0/24
