version: '3'

services:
    manager:
        build:
            context: manager/${MANAGER_MAJOR}/${MANAGER_MINOR}/${MANAGER_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=hinemos-manager-base-${MANAGER_MAJOR}.${MANAGER_MINOR}:openjdk${JAVA_VER}-${OS}
        image: hinemos-manager-${MANAGER_MAJOR}.${MANAGER_MINOR}:${MANAGER_TAG}
        ports:
            - '8080-8082:8080-8082'
            - '514:514'
            - '514:514/udp'
            - '162:162/udp'
            - '4000:4000'
        hostname: hinemos_manager
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.10
        container_name: hinemos-manager
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

    agent:
        build:
            context: agent/${AGENT_MAJOR}/${AGENT_MINOR}/${AGENT_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=hinemos-agent-base-${AGENT_MAJOR}.${AGENT_MINOR}:openjdk${JAVA_VER}-${OS}
        image: hinemos-agent-${AGENT_MAJOR}.${AGENT_MINOR}:${AGENT_TAG}
        hostname: hinemos-agent
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.11
        container_name: hinemos-agent
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

    web:
        build:
            context: web/${WEB_MAJOR}/${WEB_MINOR}/${WEB_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=hinemos-web-base-${WEB_MAJOR}.${WEB_MINOR}:openjdk${JAVA_VER}-${OS}
        image: hinemos-web-${WEB_MAJOR}.${WEB_MINOR}:${WEB_TAG}
        ports:
            - '80:80'
            #- '443:443'
        hostname: hinemos_web
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.12
        container_name: hinemos-web
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

networks:
    hinemos_net:
        ipam:
            driver: default
            config:
                - subnet: 172.31.1.0/24
