version: '3'

services:
    manager:
        build:
            context: manager/${MANAGER_MAJOR}/${MANAGER_MINOR}/${MANAGER_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=${REPOSITORY}/hinemos-manager-${JAVA_IMAGE}-${OS_IMAGE}:${MANAGER_MAJOR}.${MANAGER_MINOR}
                #- FROM_TAG=${REPOSITORY}/hinemos-manager-restored-${JAVA_IMAGE}-${OS_IMAGE}:${MANAGER_MAJOR}.${MANAGER_MINOR}
                #- FROM_TAG=${REPOSITORY}/hinemos-manager-https-${JAVA_IMAGE}-${OS_IMAGE}:${MANAGER_MAJOR}.${MANAGER_MINOR}
        image: hinemos-manager-${JAVA_IMAGE}-${OS_IMAGE}:${MANAGER_MAJOR}.${MANAGER_MINOR}-${MANAGER_TAG}
        ports:
            - '8080-8081:8080-8081'
            #- '8443-8444:8443-8444'
            - '8082:8082'
            - '514:514'
            - '514:514/udp'
            - '162:162/udp'
            #- '4000:4000' # remote debug
            #- '7100:7100' # JMX
        hostname: hinemos_manager
        networks:
            hinemos-net:
                ipv4_address: 172.31.1.10
        extra_hosts:
            - docker-host:${LOCAL_IP}
        container_name: hinemos-manager
        cap_add:
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_RESOURCE
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

    agent:
        build:
            context: agent/${AGENT_MAJOR}/${AGENT_MINOR}/${AGENT_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=${REPOSITORY}/hinemos-agent-${JAVA_IMAGE}-${OS_IMAGE}:${AGENT_MAJOR}.${AGENT_MINOR}
        image: hinemos-agent-${JAVA_IMAGE}-${OS_IMAGE}:${AGENT_MAJOR}.${AGENT_MINOR}-${AGENT_TAG}
        ports:
            - '161:161/udp'
            - '24005:24005/udp'
            #- '4001:4001' # remote debug
        hostname: hinemos-agent
        networks:
            hinemos-net:
                ipv4_address: 172.31.1.11
        extra_hosts:
            - docker-host:${LOCAL_IP}
        container_name: hinemos-agent
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

    web:
        build:
            context: web/${WEB_MAJOR}/${WEB_MINOR}/${WEB_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=${REPOSITORY}/hinemos-web-${JAVA_IMAGE}-${OS_IMAGE}:${WEB_MAJOR}.${WEB_MINOR}
        image: hinemos-web-${JAVA_IMAGE}-${OS_IMAGE}:${WEB_MAJOR}.${WEB_MINOR}-${WEB_TAG}
        ports:
            - '80:80'
            #- '443:443'
            #- '4002:4002' # remote debug
        hostname: hinemos_web
        networks:
            hinemos-net:
                ipv4_address: 172.31.1.12
        extra_hosts:
            - docker-host:${LOCAL_IP}
        container_name: hinemos-web
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

networks:
    hinemos-net:
        ipam:
            driver: default
            config:
                - subnet: 172.31.1.0/24
