version: '3'

services:
    agent:
        build:
            context: agent/${AGENT_MAJOR}/${AGENT_MINOR}/${AGENT_TAG}
            dockerfile: ../../../common/DockerfilePatch
            args:
                - FROM_TAG=${REPOSITORY}/hinemos-agent-package-${JAVA_IMAGE}-${OS_IMAGE}:${AGENT_MAJOR}.${AGENT_MINOR}
        image: hinemos-agent-${JAVA_IMAGE}-${OS_IMAGE}:${AGENT_MAJOR}.${AGENT_MINOR}-${AGENT_TAG}
        hostname: hinemos-agent
        network_mode: host
        container_name: hinemos-agent
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped
