version: '3'

services:
    manager:
        build:
            context: ./manager-${MANAGER_TAG}
            dockerfile: Dockerfile
        image: hinemos-manager:${MANAGER_TAG}
        ports:
            - '8080-8082:8080-8082'
            - '514:514'
            - '514:514/udp'
            - '162:162/udp'
            - '4000:4000'
        hostname: centos_manager
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.10
        container_name: hinemos-manager
        # privileged: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: unless-stopped

    web:
        build:
            context: ./web-${WEB_TAG}
            dockerfile: Dockerfile
        image: hinemos-web:${WEB_TAG}
        ports:
            - '80:80'
        hostname: centos_web
        networks:
            hinemos_net:
                ipv4_address: 172.31.1.11
        container_name: hinemos-web
        # privileged: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        depends_on:
            - manager
        restart: unless-stopped

networks:
    hinemos_net:
        ipam:
            driver: default
            config:
                - subnet: 172.31.1.0/24
