ARG FROM
FROM ${FROM}

RUN yum -y install https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.rpm && yum clean all
#RUN amazon-linux-extras enable corretto8
#RUN yum -y install java-1.8.0-amazon-corretto && yum clean all
